Restyled by shfmt

diff --git a/bin/gen_tfrc b/bin/gen_tfrc
--- a/bin/gen_tfrc
+++ b/bin/gen_tfrc
@@ -6,17 +6,17 @@ TARGET_FILE="$TARGET_DIR/credentials.tfrc.json"
 
 # Check if TERRAFORM_CLOUD_TOKEN is set
 if [ -z "$TERRAFORM_CLOUD_TOKEN" ]; then
-    echo "Error: TERRAFORM_CLOUD_TOKEN environment variable is not set."
-    exit 1
+  echo "Error: TERRAFORM_CLOUD_TOKEN environment variable is not set."
+  exit 1
 fi
 
 # Check if directory exists, if not, create it
 if [ ! -d "$TARGET_DIR" ]; then
-    mkdir -p "$TARGET_DIR"
+  mkdir -p "$TARGET_DIR"
 fi
 
 # Generate credentials.tfrc.json with the token
-cat > "$TARGET_FILE" << EOF
+cat >"$TARGET_FILE" <<EOF
 {
   "credentials": {
     "app.terraform.io": {
